name: Swift
on: [push]
jobs:

  swiftpm:
    name: Swift Package Manager
    runs-on: macos-latest
    steps:
    - name: Install Swift
      uses: slashmo/install-swift@v0.3.0
      with:
        version: 5.8
    - name: Checkout
      uses: actions/checkout@v2
    - name: Swift Version
      run: swift --version
    - name: Build (Debug)
      run: swift build -c debug
    - name: Build (Release)
      run: swift build -c release
  
  xcode:
    name: Xcode
    runs-on: macos-latest
    strategy:
      matrix:
        platform:
          - macOS
          - watchOS
          - tvOS
          - iOS
          - mac-catalyst
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: mxcl/Xcodebuild
        uses: mxcl/xcodebuild@v2.0.0
        with:
          platform: ${{ matrix.platform }}
